"""add_order_and_main_menu_to_personas

Revision ID: b19568f1a5d7
Revises: 396ec01a0a43
Create Date: 2025-11-26 22:27:00.898561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19568f1a5d7'
down_revision: Union[str, None] = '396ec01a0a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('order', sa.BigInteger(), nullable=True))
    op.add_column('personas', sa.Column('main_menu', sa.Boolean(), nullable=True))
    op.create_index('ix_personas_order', 'personas', ['order'], unique=False)
    op.drop_index('ix_users_premium_tier', table_name='users')
    op.drop_index('ix_users_referred_by_user_id', table_name='users')
    # ### end Alembic commands ###
    
    # Set default values for existing personas
    # main_menu=True for all existing personas
    op.execute("UPDATE personas SET main_menu = TRUE WHERE main_menu IS NULL")
    
    # Set order based on created_at (row_number) to maintain existing order
    op.execute("""
        UPDATE personas 
        SET "order" = subquery.row_num 
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) as row_num
            FROM personas
            WHERE "order" IS NULL
        ) AS subquery
        WHERE personas.id = subquery.id
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_referred_by_user_id', 'users', ['referred_by_user_id'], unique=False)
    op.create_index('ix_users_premium_tier', 'users', ['premium_tier'], unique=False)
    op.drop_index('ix_personas_order', table_name='personas')
    op.drop_column('personas', 'main_menu')
    op.drop_column('personas', 'order')
    # ### end Alembic commands ###


