"""Add Translation model for unified localization

Revision ID: d97e2ee04e72
Revises: e021a6635b20
Create Date: 2025-11-19 18:38:41.625215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd97e2ee04e72'
down_revision: Union[str, None] = 'e021a6635b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create translations table for unified localization
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'lang', name='uq_translations_key_lang')
    )
    op.create_index('ix_translations_category', 'translations', ['category'], unique=False)
    op.create_index(op.f('ix_translations_key'), 'translations', ['key'], unique=False)
    op.create_index('ix_translations_key_lang', 'translations', ['key', 'lang'], unique=False)
    op.create_index(op.f('ix_translations_lang'), 'translations', ['lang'], unique=False)
    
    # Note: Skipping unrelated table drops (system_message_* tables) to avoid dependency issues
    # These changes are not related to the translation system
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop translations table and indexes
    op.drop_index(op.f('ix_translations_lang'), table_name='translations')
    op.drop_index('ix_translations_key_lang', table_name='translations')
    op.drop_index(op.f('ix_translations_key'), table_name='translations')
    op.drop_index('ix_translations_category', table_name='translations')
    op.drop_table('translations')
    
    # Note: Skipping recreation of unrelated tables (system_message_* tables)
    # ### end Alembic commands ###


